export interface CountryDialInfo {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
  postalLabel?: string;
  postalPlaceholder?: string;
  phonePlaceholder?: string;
  hasPostalCode?: boolean;
}

export const countryDialData: CountryDialInfo[] = [
  { name: "United States", code: "US", dialCode: "+1", flag: "🇺🇸", postalLabel: "ZIP Code", postalPlaceholder: "e.g. 10001", phonePlaceholder: "e.g. (212) 555-0198", hasPostalCode: true },
  { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦", postalLabel: "Postal Code", postalPlaceholder: "e.g. M5V 2T6 or K1A 0B1", phonePlaceholder: "e.g. (416) 555-0198", hasPostalCode: true },
  { name: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧", postalLabel: "Postcode", postalPlaceholder: "e.g. SW1A 1AA or EC1A 1BB", phonePlaceholder: "e.g. 020 7946 0919", hasPostalCode: true },
  { name: "Belgium", code: "BE", dialCode: "+32", flag: "🇧🇪", postalLabel: "Postal Code", postalPlaceholder: "e.g. 1000 or 2000", phonePlaceholder: "e.g. 02 123 45 67 or 0470 12 34 56", hasPostalCode: true },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "🇦🇪", postalLabel: "Postal Code (Optional)", postalPlaceholder: "Not required in UAE", phonePlaceholder: "e.g. 50 123 4567 or 4 123 4567", hasPostalCode: false },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "🇸🇦", postalLabel: "Postal Code", postalPlaceholder: "e.g. 12271", phonePlaceholder: "e.g. 50 123 4567", hasPostalCode: true },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦", postalLabel: "Postal Code (Optional)", postalPlaceholder: "Not required in Qatar", phonePlaceholder: "e.g. 3312 3456", hasPostalCode: false },
  { name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼", postalLabel: "Postal Code (Optional)", postalPlaceholder: "e.g. 13001 (Optional)", phonePlaceholder: "e.g. 9123 4567", hasPostalCode: false },
  { name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭", postalLabel: "Block / Postal Code", postalPlaceholder: "e.g. 318", phonePlaceholder: "e.g. 3912 3456", hasPostalCode: true },
  { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲", postalLabel: "Postal Code", postalPlaceholder: "e.g. 111", phonePlaceholder: "e.g. 9123 4567", hasPostalCode: true },
  { name: "Turkey", code: "TR", dialCode: "+90", flag: "🇹🇷", postalLabel: "Posta Kodu", postalPlaceholder: "e.g. 34000", phonePlaceholder: "e.g. 212 123 45 67", hasPostalCode: true },
  { name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪", postalLabel: "Postleitzahl (PLZ)", postalPlaceholder: "e.g. 10115 or 80331", phonePlaceholder: "e.g. 030 1234567", hasPostalCode: true },
  { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷", postalLabel: "Code Postal", postalPlaceholder: "e.g. 75001 or 69001", phonePlaceholder: "e.g. 01 40 20 50 00", hasPostalCode: true },
  { name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹", postalLabel: "CAP (Codice Postale)", postalPlaceholder: "e.g. 00100 or 20121", phonePlaceholder: "e.g. 06 12345678", hasPostalCode: true },
  { name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸", postalLabel: "Código Postal", postalPlaceholder: "e.g. 28001 or 08001", phonePlaceholder: "e.g. 91 123 45 67", hasPostalCode: true },
  { name: "Netherlands", code: "NL", dialCode: "+31", flag: "🇳🇱", postalLabel: "Postcode", postalPlaceholder: "e.g. 1012 AB", phonePlaceholder: "e.g. 020 123 4567", hasPostalCode: true },
  { name: "Switzerland", code: "CH", dialCode: "+41", flag: "🇨🇭", postalLabel: "PLZ / NPA", postalPlaceholder: "e.g. 8001 or 1201", phonePlaceholder: "e.g. 044 123 45 67", hasPostalCode: true },
  { name: "Austria", code: "AT", dialCode: "+43", flag: "🇦🇹", postalLabel: "Postleitzahl", postalPlaceholder: "e.g. 1010", phonePlaceholder: "e.g. 01 1234567", hasPostalCode: true },
  { name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺", postalLabel: "Postcode", postalPlaceholder: "e.g. 2000 or 3000", phonePlaceholder: "e.g. 02 9876 5432", hasPostalCode: true },
  { name: "New Zealand", code: "NZ", dialCode: "+64", flag: "🇳🇿", postalLabel: "Postcode", postalPlaceholder: "e.g. 1010", phonePlaceholder: "e.g. 09 123 4567", hasPostalCode: true },
  { name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵", postalLabel: "Postal Code", postalPlaceholder: "e.g. 100-0001", phonePlaceholder: "e.g. 03-1234-5678", hasPostalCode: true },
  { name: "South Korea", code: "KR", dialCode: "+82", flag: "🇰🇷", postalLabel: "Postal Code", postalPlaceholder: "e.g. 03050", phonePlaceholder: "e.g. 02-1234-5678", hasPostalCode: true },
  { name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬", postalLabel: "Postal Code", postalPlaceholder: "e.g. 018956", phonePlaceholder: "e.g. 6123 4567", hasPostalCode: true },
  { name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳", postalLabel: "Postal Code", postalPlaceholder: "e.g. 100000", phonePlaceholder: "e.g. 010 1234 5678", hasPostalCode: true },
  { name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳", postalLabel: "PIN Code", postalPlaceholder: "e.g. 110001 or 400001", phonePlaceholder: "e.g. 98765 43210", hasPostalCode: true },
  { name: "Brazil", code: "BR", dialCode: "+55", flag: "🇧🇷", postalLabel: "CEP", postalPlaceholder: "e.g. 01310-100", phonePlaceholder: "e.g. (11) 91234-5678", hasPostalCode: true },
  { name: "Mexico", code: "MX", dialCode: "+52", flag: "🇲🇽", postalLabel: "Código Postal", postalPlaceholder: "e.g. 06600", phonePlaceholder: "e.g. 55 1234 5678", hasPostalCode: true },
  { name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷", postalLabel: "Código Postal", postalPlaceholder: "e.g. C1002", phonePlaceholder: "e.g. 11 1234-5678", hasPostalCode: true },
  { name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱", postalLabel: "Código Postal", postalPlaceholder: "e.g. 8320000", phonePlaceholder: "e.g. 2 2123 4567", hasPostalCode: true },
  { name: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴", postalLabel: "Código Postal", postalPlaceholder: "e.g. 110111", phonePlaceholder: "e.g. 601 123 4567", hasPostalCode: true },
  { name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬", postalLabel: "Postal Code", postalPlaceholder: "e.g. 11511", phonePlaceholder: "e.g. 02 1234 5678", hasPostalCode: true },
  { name: "South Africa", code: "ZA", dialCode: "+27", flag: "🇿🇦", postalLabel: "Postal Code", postalPlaceholder: "e.g. 2000 or 8001", phonePlaceholder: "e.g. 011 123 4567", hasPostalCode: true },
  { name: "Greece", code: "GR", dialCode: "+30", flag: "🇬🇷", postalLabel: "Postal Code", postalPlaceholder: "e.g. 105 57", phonePlaceholder: "e.g. 210 123 4567", hasPostalCode: true },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹", postalLabel: "Código Postal", postalPlaceholder: "e.g. 1000-001", phonePlaceholder: "e.g. 21 123 4567", hasPostalCode: true },
  { name: "Ireland", code: "IE", dialCode: "+353", flag: "🇮🇪", postalLabel: "Eircode / Postcode", postalPlaceholder: "e.g. D02 X285", phonePlaceholder: "e.g. 01 234 5678", hasPostalCode: true },
  { name: "Sweden", code: "SE", dialCode: "+46", flag: "🇸🇪", postalLabel: "Postnummer", postalPlaceholder: "e.g. 111 22", phonePlaceholder: "e.g. 08-123 45 67", hasPostalCode: true },
  { name: "Norway", code: "NO", dialCode: "+47", flag: "🇳🇴", postalLabel: "Postnummer", postalPlaceholder: "e.g. 0150", phonePlaceholder: "e.g. 21 23 45 67", hasPostalCode: true },
  { name: "Denmark", code: "DK", dialCode: "+45", flag: "🇩🇰", postalLabel: "Postnummer", postalPlaceholder: "e.g. 1050", phonePlaceholder: "e.g. 32 12 34 56", hasPostalCode: true },
  { name: "Finland", code: "FI", dialCode: "+358", flag: "🇫🇮", postalLabel: "Postinumero", postalPlaceholder: "e.g. 00100", phonePlaceholder: "e.g. 09 1234567", hasPostalCode: true },
  { name: "Poland", code: "PL", dialCode: "+48", flag: "🇵🇱", postalLabel: "Kod Pocztowy", postalPlaceholder: "e.g. 00-001", phonePlaceholder: "e.g. 22 123 45 67", hasPostalCode: true },
  { name: "Czech Republic", code: "CZ", dialCode: "+420", flag: "🇨🇿", postalLabel: "PSČ", postalPlaceholder: "e.g. 110 00", phonePlaceholder: "e.g. 221 123 456", hasPostalCode: true },
  { name: "Hungary", code: "HU", dialCode: "+36", flag: "🇭🇺", postalLabel: "Irányítószám", postalPlaceholder: "e.g. 1011", phonePlaceholder: "e.g. 1 234 5678", hasPostalCode: true },
  { name: "Romania", code: "RO", dialCode: "+40", flag: "🇷🇴", postalLabel: "Cod Poștal", postalPlaceholder: "e.g. 010011", phonePlaceholder: "e.g. 021 123 4567", hasPostalCode: true },
  { name: "Israel", code: "IL", dialCode: "+972", flag: "🇮🇱", postalLabel: "Postal Code", postalPlaceholder: "e.g. 6100000", phonePlaceholder: "e.g. 03-123-4567", hasPostalCode: true },
  { name: "Thailand", code: "TH", dialCode: "+66", flag: "🇹🇭", postalLabel: "Postal Code", postalPlaceholder: "e.g. 10110", phonePlaceholder: "e.g. 02 123 4567", hasPostalCode: true },
  { name: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾", postalLabel: "Poskod", postalPlaceholder: "e.g. 50450", phonePlaceholder: "e.g. 03-1234 5678", hasPostalCode: true },
  { name: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩", postalLabel: "Kode Pos", postalPlaceholder: "e.g. 10110", phonePlaceholder: "e.g. 021 12345678", hasPostalCode: true },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭", postalLabel: "ZIP Code", postalPlaceholder: "e.g. 1000", phonePlaceholder: "e.g. 02 8123 4567", hasPostalCode: true },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳", postalLabel: "Postal Code", postalPlaceholder: "e.g. 700000", phonePlaceholder: "e.g. 028 1234 5678", hasPostalCode: true },
  { name: "Hong Kong", code: "HK", dialCode: "+852", flag: "🇭🇰", postalLabel: "Postal Code (Optional)", postalPlaceholder: "Not used in HK", phonePlaceholder: "e.g. 2123 4567", hasPostalCode: false },
  { name: "Taiwan", code: "TW", dialCode: "+886", flag: "🇹🇼", postalLabel: "Postal Code", postalPlaceholder: "e.g. 100", phonePlaceholder: "e.g. 02 1234 5678", hasPostalCode: true },
  { name: "Morocco", code: "MA", dialCode: "+212", flag: "🇲🇦", postalLabel: "Code Postal", postalPlaceholder: "e.g. 20000", phonePlaceholder: "e.g. 0522 12 34 56", hasPostalCode: true },
  { name: "Jordan", code: "JO", dialCode: "+962", flag: "🇯🇴", postalLabel: "Postal Code", postalPlaceholder: "e.g. 11118", phonePlaceholder: "e.g. 06 123 4567", hasPostalCode: true },
  { name: "Lebanon", code: "LB", dialCode: "+961", flag: "🇱🇧", postalLabel: "Postal Code", postalPlaceholder: "e.g. 1107 2020", phonePlaceholder: "e.g. 01 123 456", hasPostalCode: true },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦", postalLabel: "Postal Code", postalPlaceholder: "e.g. 01001", phonePlaceholder: "e.g. 044 123 4567", hasPostalCode: true },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰", postalLabel: "Postal Code", postalPlaceholder: "e.g. 44000", phonePlaceholder: "e.g. 051 1234567", hasPostalCode: true },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩", postalLabel: "Postal Code", postalPlaceholder: "e.g. 1000", phonePlaceholder: "e.g. 02 1234567", hasPostalCode: true },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬", postalLabel: "Postal Code", postalPlaceholder: "e.g. 100001", phonePlaceholder: "e.g. 01 123 4567", hasPostalCode: true },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪", postalLabel: "Postal Code", postalPlaceholder: "e.g. 00100", phonePlaceholder: "e.g. 020 1234567", hasPostalCode: true },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭", postalLabel: "Postal Code", postalPlaceholder: "e.g. GA-123-4567", phonePlaceholder: "e.g. 030 123 4567", hasPostalCode: true },
  { name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪", postalLabel: "Código Postal", postalPlaceholder: "e.g. 15001", phonePlaceholder: "e.g. 01 123 4567", hasPostalCode: true },
  { name: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨", postalLabel: "Código Postal", postalPlaceholder: "e.g. 170150", phonePlaceholder: "e.g. 02 123 4567", hasPostalCode: true },
  { name: "Cyprus", code: "CY", dialCode: "+357", flag: "🇨🇾", postalLabel: "Postal Code", postalPlaceholder: "e.g. 1010", phonePlaceholder: "e.g. 22 123456", hasPostalCode: true },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺", postalLabel: "Code Postal", postalPlaceholder: "e.g. 1010", phonePlaceholder: "e.g. 20 12 34 56", hasPostalCode: true },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨", postalLabel: "Code Postal", postalPlaceholder: "e.g. 98000", phonePlaceholder: "e.g. 97 98 00 00", hasPostalCode: true },
  { name: "Iceland", code: "IS", dialCode: "+354", flag: "🇮🇸", postalLabel: "Póstnúmer", postalPlaceholder: "e.g. 101", phonePlaceholder: "e.g. 512 3456", hasPostalCode: true },
  { name: "Malta", code: "MT", dialCode: "+356", flag: "🇲🇹", postalLabel: "Postcode", postalPlaceholder: "e.g. VLT 1115", phonePlaceholder: "e.g. 2123 4567", hasPostalCode: true },
  { name: "Croatia", code: "HR", dialCode: "+385", flag: "🇭🇷", postalLabel: "Poštanski Broj", postalPlaceholder: "e.g. 10000", phonePlaceholder: "e.g. 01 123 4567", hasPostalCode: true },
  { name: "Bulgaria", code: "BG", dialCode: "+359", flag: "🇧🇬", postalLabel: "Пощенски код", postalPlaceholder: "e.g. 1000", phonePlaceholder: "e.g. 02 123 4567", hasPostalCode: true },
  { name: "Slovakia", code: "SK", dialCode: "+421", flag: "🇸🇰", postalLabel: "PSČ", postalPlaceholder: "e.g. 811 01", phonePlaceholder: "e.g. 02 1234 5678", hasPostalCode: true },
  { name: "Slovenia", code: "SI", dialCode: "+386", flag: "🇸🇮", postalLabel: "Poštna Številka", postalPlaceholder: "e.g. 1000", phonePlaceholder: "e.g. 01 123 45 67", hasPostalCode: true },
  { name: "Estonia", code: "EE", dialCode: "+372", flag: "🇪🇪", postalLabel: "Postiindeks", postalPlaceholder: "e.g. 10115", phonePlaceholder: "e.g. 612 3456", hasPostalCode: true },
  { name: "Latvia", code: "LV", dialCode: "+371", flag: "🇱🇻", postalLabel: "Pasta Indekss", postalPlaceholder: "e.g. LV-1050", phonePlaceholder: "e.g. 67 123 456", hasPostalCode: true },
  { name: "Lithuania", code: "LT", dialCode: "+370", flag: "🇱🇹", postalLabel: "Pašto Kodas", postalPlaceholder: "e.g. LT-01100", phonePlaceholder: "e.g. 5 123 4567", hasPostalCode: true },
  { name: "Serbia", code: "RS", dialCode: "+381", flag: "🇷🇸", postalLabel: "Poštanski Broj", postalPlaceholder: "e.g. 11000", phonePlaceholder: "e.g. 011 123 4567", hasPostalCode: true },
  { name: "Algeria", code: "DZ", dialCode: "+213", flag: "🇩🇿", postalLabel: "Code Postal", postalPlaceholder: "e.g. 16000", phonePlaceholder: "e.g. 021 12 34 56", hasPostalCode: true },
  { name: "Tunisia", code: "TN", dialCode: "+216", flag: "🇹🇳", postalLabel: "Code Postal", postalPlaceholder: "e.g. 1000", phonePlaceholder: "e.g. 71 123 456", hasPostalCode: true },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷", postalLabel: "Código Postal", postalPlaceholder: "e.g. 10101", phonePlaceholder: "e.g. 2123 4567", hasPostalCode: true },
  { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦", postalLabel: "Postal Code (Optional)", postalPlaceholder: "e.g. 0801", phonePlaceholder: "e.g. 212 3456", hasPostalCode: false },
  { name: "Dominican Republic", code: "DO", dialCode: "+1-809", flag: "🇩🇴", postalLabel: "Código Postal", postalPlaceholder: "e.g. 10101", phonePlaceholder: "e.g. 809-555-0198", hasPostalCode: true },
  { name: "Puerto Rico", code: "PR", dialCode: "+1-787", flag: "🇵🇷", postalLabel: "ZIP Code", postalPlaceholder: "e.g. 00901", phonePlaceholder: "e.g. 787-555-0198", hasPostalCode: true },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾", postalLabel: "Código Postal", postalPlaceholder: "e.g. 11000", phonePlaceholder: "e.g. 2123 4567", hasPostalCode: true },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰", postalLabel: "Postal Code", postalPlaceholder: "e.g. 00100", phonePlaceholder: "e.g. 011 234 5678", hasPostalCode: true },
  { name: "Nepal", code: "NP", dialCode: "+977", flag: "🇳🇵", postalLabel: "Postal Code", postalPlaceholder: "e.g. 44600", phonePlaceholder: "e.g. 01-4123456", hasPostalCode: true },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿", postalLabel: "Postal Code", postalPlaceholder: "e.g. 010000", phonePlaceholder: "e.g. 7172 12 34 56", hasPostalCode: true },
  { name: "Georgia", code: "GE", dialCode: "+995", flag: "🇬🇪", postalLabel: "Postal Code", postalPlaceholder: "e.g. 0105", phonePlaceholder: "e.g. 032 212 3456", hasPostalCode: true },
  { name: "Armenia", code: "AM", dialCode: "+374", flag: "🇦🇲", postalLabel: "Postal Code", postalPlaceholder: "e.g. 0010", phonePlaceholder: "e.g. 10 123456", hasPostalCode: true },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: "🇦🇿", postalLabel: "Postal Code", postalPlaceholder: "e.g. AZ1000", phonePlaceholder: "e.g. 12 123 45 67", hasPostalCode: true },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998", flag: "🇺🇿", postalLabel: "Postal Code", postalPlaceholder: "e.g. 100000", phonePlaceholder: "e.g. 71 123 45 67", hasPostalCode: true },
  { name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶", postalLabel: "Postal Code", postalPlaceholder: "e.g. 10011", phonePlaceholder: "e.g. 01 123 4567", hasPostalCode: true }
];

export const getDialCodeByCountry = (countryName: string): string => {
  if (!countryName) return "+1";
  const found = countryDialData.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase()
  );
  return found ? found.dialCode : "+1";
};

export const getCountryDialInfo = (countryName: string): CountryDialInfo => {
  if (!countryName) {
    return countryDialData[0];
  }
  const found = countryDialData.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase()
  );
  if (found) return found;

  return {
    name: countryName,
    code: "US",
    dialCode: "+1",
    flag: "🌐",
    postalLabel: "Postal / ZIP Code",
    postalPlaceholder: "e.g. Postal Code",
    phonePlaceholder: "e.g. Local Phone Number",
    hasPostalCode: true
  };
};

export const countries = Array.from(new Set([
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
  "China",
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Turkey",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Egypt",
  "South Africa",
  "Greece",
  "Portugal",
  "Ireland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Israel",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Hong Kong",
  "Taiwan",
  "Morocco",
  "Jordan",
  "Lebanon",
  "Ukraine",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Peru",
  "Ecuador",
  "Cyprus",
  "Luxembourg",
  "Monaco",
  "Iceland",
  "Malta",
  "Croatia",
  "Bulgaria",
  "Slovakia",
  "Slovenia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Serbia",
  "Algeria",
  "Tunisia",
  "Costa Rica",
  "Panama",
  "Dominican Republic",
  "Puerto Rico",
  "Uruguay",
  "Sri Lanka",
  "Nepal",
  "Kazakhstan",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Uzbekistan",
  "Iraq",
  "Afghanistan",
  "Albania",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Bahamas",
  "Barbados",
  "Belarus",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brunei",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo",
  "Cuba",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Dominica",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Gabon",
  "Gambia",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guyana",
  "Haiti",
  "Honduras",
  "Iran",
  "Jamaica",
  "Kiribati",
  "Kosovo",
  "Kyrgyzstan",
  "Laos",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Madagascar",
  "Malawi",
  "Maldives",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Moldova",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nicaragua",
  "Niger",
  "North Korea",
  "North Macedonia",
  "Palestine",
  "Papua New Guinea",
  "Paraguay",
  "Russia",
  "Rwanda",
  "Samoa",
  "San Marino",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "Sudan",
  "Suriname",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Uganda",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Yemen",
  "Zambia",
  "Zimbabwe"
])).sort();
